# Generated by Django 4.2.7 on 2023-11-06 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Enter the valid age.'), django.core.validators.MaxValueValidator(limit_value=100, message='Enter the valid age.')]),
        ),
    ]
